name: "CI Tests"

on: ["push", "pull_request"]

jobs:
  build:
    name: "Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        ruby: ["2.6"]
        rails: ["5.2", "6.0", "master"]

    env:
      RAILS_VERSION: "${{ matrix.rails }}"

    steps:
    - uses: "actions/checkout@v2"

    - name: "Install Ruby ${{ matrix.ruby }}"
      uses: "ruby/setup-ruby@v1"
      with:
        ruby-version: "${{ matrix.ruby }}"

    - name: "Generate lockfile"
      run: |
        bundle config path vendor/bundle
        bundle lock

    - uses: "actions/cache@v1"
      with:
        path: "vendor/bundle"
        key: bundle-${{ hashFiles('Gemfile.lock') }}

    - name: "Install Dependencies"
      run: |
        sudo apt-get update
        sudo apt-get -yqq install libsqlite3-dev chromium-browser

        bundle install --jobs 4 --retry 3

        bin/rails app:webdrivers:chromedriver:update

    - name: "Prepare for Tests"
      run: |
        bin/rails db:create db:migrate db:test:prepare

    - name: "Run Engine Tests"
      run: |
        bin/rails test

    - name: "Run System Tests"
      run: |
        bin/rails app:test:system
